CREATE TABLE `toc_file` (
  `IDX` int(11) NOT NULL AUTO_INCREMENT,
  `BOARD_IDX` int(11) NOT NULL,
  `ORIGINAL_FILE_NAME` text COLLATE utf8_bin NOT NULL,
  `STORED_FILE_NAME` varchar(36) COLLATE utf8_bin NOT NULL,
  `FILE_SIZE` int(11) NOT NULL,
  `CREA_DTM` date DEFAULT NULL,
  `CREA_ID` varchar(30) COLLATE utf8_bin DEFAULT NULL,
  `DEL_GB` varchar(1) COLLATE utf8_bin DEFAULT 'N',
  PRIMARY KEY (`IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COLLATE=utf8_bin